### ISSUE TITLE
XF not work

### ISSUE THREAD

**Issue by brux88** [matteobortolazzo/HtmlLabelPlugin#14]
h, i have this error:
Java.Lang.IndexOutOfBoundsException: replace (-1 ... 0) starts before 0

**Comment by matteobortolazzo** [comment]
Can you provide me an example, please?

**Comment by matteobortolazzo** [comment]
I'll close it for now

**Comment by castrojr913** [comment]
@matteobortolazzo Friend, i confirm the issue happens too on Android with just using the tag on XAML. Don't worry about "I" letter; It's due to Pidcat logs. Notice that there's some issue on HtmlLabelRender on line 82. 

Error Trace: 

_Java.Lang.IndexOutOfBoundsException: replace (-1 ... 0) starts before 0
                         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0
                         at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Inte
                            rop.JniArgumentValue* args) [0x00069] in <e736913786c2475188869561ae512b72>:0
                         at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop
                            .JniArgumentValue* parameters) [0x0002a] in <e736913786c2475188869561ae512b72>:0
                         at Android.Text.SpannableStringBuilder.Delete (System.Int32 start, System.Int32 end) [0x00035] in <8211f1f12f9e45838d631abf63e51c79>:0
                         at Plugin.HtmlLabel.Android.HtmlLabelRenderer.RemoveLastChar (Android.Text.ISpanned text) [0x00006] in C:\Users\Matteo\Documents\GitHub\HtmlLabelPlugin
                            \src\Plugin.HtmlLabel.Android\HtmlLabelRenderer.cs:88
                         at Plugin.HtmlLabel.Android.HtmlLabelRenderer.UpdateText () [0x00092] in C:\Users\Matteo\Documents\GitHub\HtmlLabelPlugin\src\Plugin.HtmlLabel.Android\
                            HtmlLabelRenderer.cs:82_
                         at Plugin.HtmlLabel.Android.HtmlLabelRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00010] in C:\U
                            sers\Matteo\Documents\GitHub\HtmlLabelPlugin\src\Plugin.HtmlLabel.Android\HtmlLabelRenderer.cs:29
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000b1] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:176
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.ScrollViewContainer.set_ChildView (Xamarin.Forms.View value) [0x0002f] in D:\agent\_work\1\s\Xamarin.Forms.Platform.A
                            ndroid\Renderers\ScrollViewContainer.cs:33
                         I    at Xamarin.Forms.Platform.Android.ScrollViewRenderer.LoadContent () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollView
                            Renderer.cs:294
                         I    at Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x000a6] in D:\agent\_work\1\s\Xamarin.Forms.Pla
                            tform.Android\Renderers\ScrollViewRenderer.cs:87
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00024] in D:\agent\
                            _work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRender
                            er oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00044] in D:\agent\_work\1\s\Xamarin.Forms.Platform.And
                            roid\VisualElementPackager.cs:97
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x
                            00104] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231
                         I    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs
                            :76
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x0000
                            7] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000ce] in D:\agent\_work\1\s\Xamarin.Forms.Platfor
                            m.Android\VisualElementRenderer.cs:179
                         I    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.Vis
                            ualElement element) [0x00027] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125
                         I    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager,
                             Android.Content.Context context) [0x00036] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:361
                         I    at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, A
                            ndroid.OS.Bundle savedInstanceState) [0x00008] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:67
                         I    at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, Syste
                            m.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00020] in <40bb5a57295c
                            4f648daa62e9e7aa774b>:0
                         I    at (wrapper dynamic-method) System.Object:e1f2710c-f303-4dbb-bb01-55f853b007c5 (intptr,intptr,intptr,intptr,intptr)
                         I    --- End of managed Java.Lang.IndexOutOfBoundsException stack trace ---
                         I  java.lang.IndexOutOfBoundsException: replace (-1 ... 0) starts before 0
                         I      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1021)
                         I      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:441)
                         I      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
                         I      at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
                         I      at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
                         I      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                         I      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                         I      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                         I      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                         I      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                         I      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                         I      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                         I      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                         I      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                         I      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                         I      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                         I      at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2369)
                         I      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                         I      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                         I      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                         I      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                         I      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                         I      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                         I      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                         I      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                         I      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                         I      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                         I      at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2369)
                         I      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                         I      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                         I      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                         I      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                         I      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                         I      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                         I      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                         I      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                         I      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                         I      at android.os.Handler.handleCallback(Handler.java:733)
                         I      at android.os.Handler.dispatchMessage(Handler.java:95)
                         I      at android.os.Looper.loop(Looper.java:136)
                         I      at android.app.ActivityThread.main(ActivityThread.java:5584)
                         I      at java.lang.reflect.Method.invokeNative(Native Method)
                         I      at java.lang.reflect.Method.invoke(Method.java:515)
                         I      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                         I      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                         I      at dalvik.system.NativeStart.main(Native Method)

**Comment by matteobortolazzo** [comment]
Thanks, I suspected I was something like that but It's strange because I always check for empty string. I'll check later

**Comment by matteobortolazzo** [comment]
Solved in [2.1.4](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.1.4)

**Comment by koystinen** [comment]
this still happens to me in latest version... seems to be causing by text strings containing single space

**Comment by matteobortolazzo** [comment]
Ok I'll check
